name 'servers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures servers'
long_description 'Installs/Configures servers'
version '0.1.0'
